SCALRCORE-21039 - Scalr Provider > Add support for Run Scheduler
Scalr/terraform-provider-scalr pull request #124
Opened 2022-04-10 22:35 UTC by soltysss

### Changelog
* [ ] I have updated CHANGELOG.md according to [CONTRIBUTING.md](../CONTRIBUTING.md)

### Documentation
* [ ] I have updated resource/data source documentation in [docs](../docs)

### State
* [ ] My changes affect the state
* [ ] I have included a state migration and a unit test for it

2022-04-27 08:49 UTC, petroprotsakh approved these changes

2022-04-29 09:47 UTC, mermoldy requested changes

2022-04-29 09:47 UTC, mermoldy commented on scalr/resource_scalr_workspace_run_schedule.go
> +		"[DEBUG] Setting run schdules for workspace ID: %s, apply: %s, destroy: %s",
@soltysss typo in "schdules"

2022-05-02 10:36 UTC, mermoldy commented on scalr/resource_scalr_workspace_run_schedule.go
> +			"[DEBUG] Setting run schdules for workspace ID: %s, apply: %s, destroy: %s",
@soltysss one more :)

2022-05-02 10:36 UTC, mermoldy approved these changes

2022-05-10 08:42 UTC, merged