SCALRCORE-21894 Scalr Provider > Error "Invalid Relationship" while switching between module and vcs provider
Scalr/terraform-provider-scalr pull request #130
Opened 2022-05-10 13:39 UTC by RomanMytsko

### Changelog
* [x] I have updated CHANGELOG.md according to [CONTRIBUTING.md](../CONTRIBUTING.md)

### Documentation
* [ ] I have updated resource/data source documentation in [docs](../docs)

### State
* [ ] My changes affect the state
* [ ] I have included a state migration and a unit test for it

2022-05-16 15:08 UTC, brezitskiy commented on CHANGELOG.md
> +- `scalr_workspace`: vcs_repo and vcs_provider_id have to passed together ([#130](https://github.com/Scalr/terraform-provider-scalr/pull/130))
```suggestion
- `scalr_workspace`: vcs_repo and vcs_provider_id have to be passed simultaneously ([#130](https://github.com/Scalr/terraform-provider-scalr/pull/130))
```

2022-05-17 10:26 UTC, mermoldy requested changes

2022-05-17 10:26 UTC, mermoldy commented on scalr/resource_scalr_workspace.go
> +				RequiredWith:  []string{"vcs_provider_id"},
@RomanMytsko we need to cover new changes with tests

2022-05-18 16:24 UTC, mermoldy approved these changes

2022-05-23 08:58 UTC, merged