SCALRCORE-16880 Provider > Update readme and add more detailed dev instructions
Scalr/terraform-provider-scalr pull request #18
Opened 2020-09-04 11:21 UTC by lbn

### Changelog

* [ ] I have updated CHANGELOG.md

2020-09-07 11:57 UTC, oliaboo requested changes

2020-09-07 11:57 UTC, oliaboo commented on README.md
> +The Scalr Terraform provider can be used to manage the components within they Scalr IaCP.
`within they Scalr IaCP` ?

2020-09-07 11:57 UTC, oliaboo commented on README.md
> +## Developing the provider
I think, developing the provider part may go to the separate doc - where migrations process should be described as well as testing provider locally (incl. `CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build`)

2020-09-08 12:43 UTC, oliaboo approved these changes

2020-09-08 12:59 UTC, emocharnik commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] My changes affect the state
👍

2020-09-08 13:03 UTC, emocharnik commented on README.md
> +The acceptance tests assume that the installation has an environment with ID `existing-env`
with ID?

2020-09-08 13:22 UTC, dmytrechko commented on README.md
> +The acceptance tests assume that the installation has an environment with ID `existing-env`
Думаю, в майбутньому краще перевести на канонічні {prefix}-{15 from hex32} - e.g: ws-11111111, env-1111111 
- по суті подібні ідшки не повинні проходити валідацію і це колись може вистрелити

2020-09-08 15:20 UTC, merged