SCALRCORE-23592: Provider configurations > Custom > Sensitive paramet…
Scalr/terraform-provider-scalr pull request #182
Opened 2022-10-06 18:46 UTC by kozliuk

…ers and attributes must be immutable

### Changelog
* [ ] I have updated CHANGELOG.md according to [CONTRIBUTING.md](../CONTRIBUTING.md)

### Documentation
* [ ] I have updated resource/data source documentation in [docs](../docs)

### State
* [ ] My changes affect the state
* [ ] I have included a state migration and a unit test for it

2022-10-06 19:48 UTC, DayS1eeper requested changes

2022-10-06 19:48 UTC, DayS1eeper commented on scalr/resource_scalr_provider_configuration.go
> +		} else if currentArgument.Sensitive && !(*configArgumentCreateOption.Sensitive) {
```suggestion
		if !exists ||  currentArgument.Sensitive && !(*configArgumentCreateOption.Sensitive) {
```

2022-10-06 19:50 UTC, kozliuk commented on scalr/resource_scalr_provider_configuration.go
> +		} else if currentArgument.Sensitive && !(*configArgumentCreateOption.Sensitive) {
@DayS1eeper хіба не впаде? якшо перше false то піде в настпну перевірку, а ітем не існує?

2022-10-06 19:51 UTC, kozliuk commented on scalr/resource_scalr_provider_configuration.go
> +		} else if currentArgument.Sensitive && !(*configArgumentCreateOption.Sensitive) {
я того сплітанув

2022-10-06 19:54 UTC, kozliuk commented on scalr/resource_scalr_provider_configuration.go
> +		} else if currentArgument.Sensitive && !(*configArgumentCreateOption.Sensitive) {
згоден)

2022-10-06 19:55 UTC, DayS1eeper commented on scalr/resource_scalr_provider_configuration.go
> +		} else if currentArgument.Sensitive && !(*configArgumentCreateOption.Sensitive) {
if `!exists` returns true, the second part of condition is not evaluated, because operator is `||`.

2022-10-06 19:56 UTC, kozliuk commented on scalr/resource_scalr_provider_configuration.go
> +		} else if currentArgument.Sensitive && !(*configArgumentCreateOption.Sensitive) {
gotcha

2022-10-06 19:58 UTC, DayS1eeper commented on scalr/resource_scalr_provider_configuration.go
> +		} else if currentArgument.Sensitive && !(*configArgumentCreateOption.Sensitive) {
https://go.dev/ref/spec 
```
The right operand is evaluated conditionally.
```

2022-10-07 07:47 UTC, DayS1eeper approved these changes

2022-10-13 09:36 UTC, merged