SCALRCORE-24972 [tf-provider] Scalr Provider > Provider configuration > Separate resource to make a provider configuration default in environment
Scalr/terraform-provider-scalr pull request #205
Opened 2023-01-31 09:48 UTC by RomanMytsko

### Changelog
* [ ] I have updated CHANGELOG.md according to [CONTRIBUTING.md](../CONTRIBUTING.md)

### Documentation
* [ ] I have updated resource/data source documentation in [docs](../docs)

### State
* [ ] My changes affect the state
* [ ] I have included a state migration and a unit test for it

2023-02-06 15:02 UTC, DayS1eeper approved these changes

2023-02-06 23:11 UTC, petroprotsakh requested changes

2023-02-06 23:11 UTC, petroprotsakh commented on scalr/resource_scalr_provider_configuration_default.go
> +	_, err = scalrClient.Environments.Update(ctx, environment.ID, updateOpts)
This won't work as expected. Only the last one resource to create will succeed; others will produce inconsistent results on read (parallelism again).

2023-02-07 09:18 UTC, petroprotsakh commented on scalr/resource_scalr_provider_configuration_default.go
> +	resourceScalrProviderConfigurationDefaultMutex.Lock()
This should do the trick for now.
However the root cause is in the API design here, not provider.
May be we should consider having `/environment/<env-id>/relationships/default-provider-configurations` endpoints for granular defaults management.
cc @DayS1eeper

2023-02-07 09:24 UTC, petroprotsakh approved these changes

2023-02-07 10:08 UTC, emocharnik commented on docs/resources/scalr_provider_configuration_default.md
> +Provider configuration should be in list of environment identifiers that the provider configuration is shared to.
@RomanMytsko:
> To make the provider configuration default, it must be shared with the specified environment. See the definition of the resource [scalr_provider_configuration](https://github.com/Scalr/terraform-provider-scalr/blob/develop/docs/resources/scalr_provider_configuration.md) and attribute `environments` to learn more.

2023-02-09 18:00 UTC, merged