SCALRCORE-16736: Create Drone pipeline for linting/unit tests
Scalr/terraform-provider-scalr pull request #23
Opened 2020-10-01 16:38 UTC by vmotso

SCALRCORE-16736

### Changelog
* [ ] I have updated CHANGELOG.md

### Documentation
* [ ] I have updated resource/data source documentation in [website/docs](https://github.com/Scalr/terraform-provider-scalr/tree/develop/website/docs)

### State
* [ ] My changes affect the state
* [ ] I have included a state migration and a unit test for it

2020-10-05 08:45 UTC, vmotso commented on .github/workflows/default.yml
> +name: default
@lbn  I have doubts about the pipeline, jobs, steps naming. Maybe you can suggest something.

2020-10-05 09:47 UTC, lbn requested changes

2020-10-05 09:47 UTC, lbn commented on .github/workflows/default.yml
> +      - name: Set up go 1.11.4
Readme says 1.13.

2020-10-05 09:47 UTC, lbn commented on .github/workflows/default.yml
> +        run: test -z $(gofmt -l .)
golangci-lint can also run this checker. [Just need to enable it explicitly](https://golangci-lint.run/usage/linters#disabled-by-default-linters--e--enable)

2020-10-05 15:32 UTC, vmotso commented on .golangci.yml
> +  exclude-rules:
To ensure all checks just skips tests related files.

2020-10-06 09:10 UTC, lbn approved these changes

2020-10-07 06:28 UTC, merged