SCALRCORE-24801 Integrations > Webhook update provider resource
Scalr/terraform-provider-scalr pull request #234
Opened 2023-04-12 07:30 UTC by petroprotsakh

### Changelog
* [ ] I have updated CHANGELOG.md according to [CONTRIBUTING.md](../CONTRIBUTING.md)

### Documentation
* [ ] I have updated resource/data source documentation in [docs](../docs)

### State
* [ ] My changes affect the state
* [ ] I have included a state migration and a unit test for it

2023-04-12 10:16 UTC, DayS1eeper requested changes

2023-04-13 14:47 UTC, petroprotsakh commented on scalr/resource_scalr_webhook.go
>  	}
@DayS1eeper It sets the environments to `[]`, so yes.

2023-04-14 09:28 UTC, DayS1eeper approved these changes

2023-04-14 09:28 UTC, DayS1eeper commented on scalr/data_source_scalr_webhook.go
> +	}
typo

2023-04-21 07:15 UTC, emocharnik commented
@petroprotsakh, Pull request has conflicts with base branch

2023-04-21 07:30 UTC, emocharnik commented
@petroprotsakh, Pull request has conflicts with base branch

2023-04-21 07:45 UTC, emocharnik commented
@petroprotsakh, Some non-required builds are failing or stuck.

2023-04-21 09:30 UTC, merged