SCALRCORE-27660
Scalr/terraform-provider-scalr pull request #271
Opened 2023-08-18 11:05 UTC by artemvang

### Changelog
* [ ] I have updated CHANGELOG.md according to [CONTRIBUTING.md](../CONTRIBUTING.md)

### Documentation
* [ ] I have updated resource/data source documentation in [docs](../docs)

### State
* [ ] My changes affect the state
* [ ] I have included a state migration and a unit test for it

2023-08-18 15:29 UTC, maratkomarov commented
@artemvang upload-dev свалился Error: Failed to update network mirror: Callback must be a function. Received undefined.

2023-08-18 15:55 UTC, maratkomarov requested changes

2023-08-18 15:55 UTC, maratkomarov commented on .github/workflows/upstream.yml
> +    runs-on: [standart-2-amd64]
@artemvang  typo: standar**d**

2023-08-21 09:47 UTC, artemvang commented on .github/workflows/upstream.yml
> +    runs-on: [standart-2-amd64]
@maratkomarov all `runs-on` returned back to `ubuntu-latest`

2023-08-21 17:32 UTC, maratkomarov commented on .github/workflows/upstream.yml
> +    runs-on: [standart-2-amd64]
оке

2023-08-21 21:47 UTC, maratkomarov approved these changes

2023-08-22 07:45 UTC, merged