SCALRCORE-17105: Use Preview Profile
Scalr/terraform-provider-scalr pull request #40
Opened 2020-11-16 14:22 UTC by vmotso

### Changelog
* [ ] I have updated CHANGELOG.md

### Documentation
* [ ] I have updated resource/data source documentation in [website/docs](https://github.com/Scalr/terraform-provider-scalr/tree/develop/website/docs)

### State
* [ ] My changes affect the state
* [ ] I have included a state migration and a unit test for it

2020-11-27 06:13 UTC, vmotso commented
Tests are passed: https://drone.scalr-labs.net/Scalr/int-terraform-provider-scalr/174

2020-11-27 17:08 UTC, lbn requested changes

2020-11-27 17:08 UTC, lbn commented on scalr/resource_scalr_endpoint.go
> +	if SecretKey, ok := d.GetOk("secret_key"); ok {
Needs to be secretKey. Title case only for struct fields you want to make public.

Also there is another `d.Get` for the same key after this if statement.

2020-12-01 09:16 UTC, lbn approved these changes

2020-12-02 10:16 UTC, merged